# Generated by Django 6.1.1 on 2026-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('observacoes', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
            ],
            options={
                'permissions': [('can_create_resources', 'Pode criar recursos'), ('can_delete_resources', 'Pode excluir recursos'), ('can_edit_resources', 'Pode editar recursos')],
            },
        ),
    ]
