# Generated by Django 6.1.1 on 2026-09-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
    ]
