# Generated by Django 6.1.1 on 2026-09-14 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_alter_resource_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_modelos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
